'use client';
import React, { useState, useEffect, useCallback } from 'react';
import { Download, Search, Loader2, AlertCircle } from 'lucide-react';
import { TxHashLink } from '@/components/TxHashLink';
import { dbOps, PayRun } from '@/lib/db';
import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

export default function PaymentHistoryPage() {
  const [payRuns, setPayRuns] = useState<PayRun[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [search, setSearch] = useState('');

  const orgId = "org_demo"; // Linked to current org

  const fetchHistory = useCallback(async () => {
    setLoading(true);
    try {
      const data = await dbOps.getPayRunsByOrg(orgId);
      setPayRuns(data.sort((a, b) => (b.createdAt?.seconds || 0) - (a.createdAt?.seconds || 0)));
    } catch (err) {
      console.error(err);
      setError("Failed to load payment history");
    } finally {
      setLoading(false);
    }
  }, [orgId]);

  useEffect(() => {
    const init = async () => {
      await fetchHistory();
    };
    init();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const generatePDF = (run: PayRun) => {
    const doc = new jsPDF() as any;
    
    doc.setFillColor(10, 10, 11);
    doc.rect(0, 0, 210, 297, 'F');
    
    doc.setTextColor(244, 232, 255);
    doc.setFont("helvetica", "italic");
    doc.setFontSize(24);
    doc.text("HushHush Pay", 20, 30);
    
    doc.setDrawColor(176, 38, 255);
    doc.setLineWidth(0.5);
    doc.line(20, 35, 80, 35);
    
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text("PAYROLL REPORT: CONFIDENTIAL", 20, 45);
    
    doc.setFontSize(12);
    doc.text(`Period: ${run.period}`, 20, 60);
    doc.text(`Run ID: ${run.id}`, 20, 68);
    doc.text(`Tx Hash: ${run.txHash || 'N/A'}`, 20, 76);
    doc.text(`Computation ID: ${run.computationId || 'N/A'}`, 20, 84);
    
    doc.autoTable({
      startY: 100,
      head: [['Metric', 'Value']],
      body: [
        ['Status', run.status.toUpperCase()],
        ['Employees Paid', run.employeeCount.toString()],
        ['Aggregate Spend (USDC)', run.aggregateUsdc.toLocaleString()],
        ['Timestamp', run.createdAt?.seconds ? new Date(run.createdAt.seconds * 1000).toLocaleString() : 'N/A']
      ],
      theme: 'plain',
      styles: { textColor: [244, 232, 255], fillColor: [20, 0, 40] },
      headStyles: { fillColor: [38, 0, 77], textColor: [176, 38, 255] }
    });
    
    doc.setFontSize(8);
    doc.text("Generated by HushHush Pay. All individual salaries remain encrypted on the Arcium Network.", 20, 280);
    
    doc.save(`HushHush_Report_${run.period.replace(/\s+/g, '_')}.pdf`);
  };

  const filteredRuns = payRuns.filter(r => 
    r.period.toLowerCase().includes(search.toLowerCase()) || 
    r.txHash?.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="space-y-8 animate-in fade-in duration-500">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-playfair italic text-amber tracking-tight mb-2">Payment History</h1>
          <p className="text-[10px] uppercase text-white/40 tracking-widest">Timeline of past pay runs and MPC computations.</p>
        </div>
        <div className="flex items-center gap-3">
          <div className="relative">
            <Search className="absolute left-4 top-3 text-white/40" size={14} />
            <input 
              type="text" 
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              placeholder="Filter by period or tx hash..." 
              className="pl-10 pr-4 py-3 bg-gray-900 border border-white/5 text-[11px] uppercase tracking-widest text-white/80 focus:border-amber outline-none w-full sm:w-72 placeholder:opacity-40"
            />
          </div>
        </div>
      </div>

      {error && (
        <div className="p-4 bg-red-900/20 border border-red-500/50 text-red-400 text-xs flex items-center gap-3">
          <AlertCircle size={16} /> {error}
        </div>
      )}

      <div className="space-y-4 relative min-h-[300px]">
        {loading && (
          <div className="absolute inset-0 flex items-center justify-center bg-obsidian/40 backdrop-blur-sm z-10">
            <Loader2 className="animate-spin text-amber" size={32} />
          </div>
        )}

        {/* Timeline line */}
        <div className="absolute left-[28px] top-6 bottom-6 w-[1px] bg-white/10 hidden md:block" />
        
        {filteredRuns.length === 0 && !loading && (
          <div className="text-center py-20 text-white/40 italic">
            No payment records found.
          </div>
        )}

        {filteredRuns.map((run) => (
          <div key={run.id} className="relative flex flex-col md:flex-row gap-8 md:items-start group">
            
            <div className="hidden md:flex flex-col items-center pt-6 z-10 w-14 shrink-0">
              <div className="w-2 h-2 bg-teal shadow-[0_0_8px_rgba(0,201,177,0.5)] border border-obsidian" />
            </div>

            <div className="flex-1 bg-gray-900 border border-white/5 p-8 hover:border-amber/50 transition-colors">
              <div className="flex flex-col md:flex-row md:items-center justify-between mb-8 pb-6 border-b border-white/5">
                <div>
                  <h3 className="text-xl font-playfair italic text-white tracking-tight">{run.period}</h3>
                  <div className="flex items-center gap-5 mt-3 text-[11px] uppercase tracking-widest font-dm-mono">
                    <span className="text-white/40">Tx: {run.txHash ? <TxHashLink hash={run.txHash} /> : 'N/A'}</span>
                    <span className="text-white/20">|</span>
                    <span className="text-white/40">ID: {run.computationId || 'N/A'}</span>
                  </div>
                </div>
                
                <div className="mt-6 md:mt-0 flex items-center gap-6">
                  <span className={`px-3 py-1 ${run.status === 'complete' ? 'bg-teal/5 text-teal border-teal/20' : 'bg-amber/5 text-amber border-amber/20'} text-[10px] uppercase tracking-widest border`}>
                    {run.status}
                  </span>
                  <button 
                    onClick={() => generatePDF(run)}
                    className="flex items-center gap-2 px-6 py-2 border border-white/20 hover:bg-white hover:text-black text-[11px] uppercase tracking-widest text-white transition-colors"
                  >
                    <Download size={14} />
                    Report (PDF)
                  </button>
                </div>
              </div>

              <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
                <div>
                  <p className="text-white/40 text-[10px] uppercase tracking-widest mb-2">Employees Paid</p>
                  <p className="text-2xl font-dm-mono text-white/90 font-light">{run.employeeCount}</p>
                </div>
                <div className="col-span-2">
                  <p className="text-white/40 text-[10px] uppercase tracking-widest mb-2 flex items-center gap-3">
                    Aggregate Spend (USDC)
                    <span className="inline-block px-2 py-1 text-[9px] uppercase tracking-widest bg-teal/5 text-teal border border-teal/20">MPC REVEAL</span>
                  </p>
                  <p className="text-3xl font-dm-mono text-amber font-light">
                      {run.aggregateUsdc.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                  </p>
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
